### ISSUE TITLE
Livesplit probably doesnt see project 64 installed

### ISSUE THREAD

**Issue by marnick100** [fmichea/sm64-livesplit-autosplitter#19] opened 2023-04-25 10:04 UTC
Hello it seems like it doesnt see project 64 (It doesnt even start the timer

**Comment by fmichea** [comment] 2024-03-04 20:37
Can't believe I missed this for so long, this can be caused by different issues. Sometimes just restarting livesplit and project64 is enough. If one but not both runs as administrator that could be the issue as well (would recommend running neither as administrator). This also requires PJ64 1.6, no other version will allow controlling the timer.

I'll close this issue since it is so old, but feel free to reply and re-open if this is still an issue. The SM64 discord is also very helpful with such issues if you prefer direct help.

**Closed as completed by fmichea** 2024-03-04 20:37 UTC
